/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _object_data_t_h
#define _object_data_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "categorized_data_t.h"
typedef struct _object_data_t object_data_t;
struct _object_data_t
{
    int64_t    utime;
    int32_t    id;
    int32_t    num_cat;
    categorized_data_t *cat_dat;
    double     pos[6];
    double     bbox[2][3];
};

object_data_t   *object_data_t_copy(const object_data_t *p);
void object_data_t_destroy(object_data_t *p);

typedef struct _object_data_t_subscription_t object_data_t_subscription_t;
typedef void(*object_data_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const object_data_t *msg, void *user);

int object_data_t_publish(lcm_t *lcm, const char *channel, const object_data_t *p);
object_data_t_subscription_t* object_data_t_subscribe(lcm_t *lcm, const char *channel, object_data_t_handler_t f, void *userdata);
int object_data_t_unsubscribe(lcm_t *lcm, object_data_t_subscription_t* hid);
int object_data_t_subscription_set_queue_capacity(object_data_t_subscription_t* subs,
                              int num_messages);


int  object_data_t_encode(void *buf, int offset, int maxlen, const object_data_t *p);
int  object_data_t_decode(const void *buf, int offset, int maxlen, object_data_t *p);
int  object_data_t_decode_cleanup(object_data_t *p);
int  object_data_t_encoded_size(const object_data_t *p);

// LCM support functions. Users should not call these
int64_t __object_data_t_get_hash(void);
int64_t __object_data_t_hash_recursive(const __lcm_hash_ptr *p);
int     __object_data_t_encode_array(void *buf, int offset, int maxlen, const object_data_t *p, int elements);
int     __object_data_t_decode_array(const void *buf, int offset, int maxlen, object_data_t *p, int elements);
int     __object_data_t_decode_array_cleanup(object_data_t *p, int elements);
int     __object_data_t_encoded_array_size(const object_data_t *p, int elements);
int     __object_data_t_clone_array(const object_data_t *p, object_data_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
