/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _robot_command_t_h
#define _robot_command_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _robot_command_t robot_command_t;
struct _robot_command_t
{
    int64_t    utime;
    int8_t     updateDest;
    double     dest[6];
    char*      action;
};
 
robot_command_t   *robot_command_t_copy(const robot_command_t *p);
void robot_command_t_destroy(robot_command_t *p);

typedef struct _robot_command_t_subscription_t robot_command_t_subscription_t;
typedef void(*robot_command_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const robot_command_t *msg, void *user);

int robot_command_t_publish(lcm_t *lcm, const char *channel, const robot_command_t *p);
robot_command_t_subscription_t* robot_command_t_subscribe(lcm_t *lcm, const char *channel, robot_command_t_handler_t f, void *userdata);
int robot_command_t_unsubscribe(lcm_t *lcm, robot_command_t_subscription_t* hid);
int robot_command_t_subscription_set_queue_capacity(robot_command_t_subscription_t* subs, 
                              int num_messages);


int  robot_command_t_encode(void *buf, int offset, int maxlen, const robot_command_t *p);
int  robot_command_t_decode(const void *buf, int offset, int maxlen, robot_command_t *p);
int  robot_command_t_decode_cleanup(robot_command_t *p);
int  robot_command_t_encoded_size(const robot_command_t *p);

// LCM support functions. Users should not call these
int64_t __robot_command_t_get_hash(void);
int64_t __robot_command_t_hash_recursive(const __lcm_hash_ptr *p);
int     __robot_command_t_encode_array(void *buf, int offset, int maxlen, const robot_command_t *p, int elements);
int     __robot_command_t_decode_array(const void *buf, int offset, int maxlen, robot_command_t *p, int elements);
int     __robot_command_t_decode_array_cleanup(robot_command_t *p, int elements);
int     __robot_command_t_encoded_array_size(const robot_command_t *p, int elements);
int     __robot_command_t_clone_array(const robot_command_t *p, robot_command_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
