/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package kinect.lcmtypes;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class robot_command_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public boolean updateDest;
    public double dest[];
    public String action;
 
    public robot_command_t()
    {
        dest = new double[6];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x27beb0b89a7b051bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(kinect.lcmtypes.robot_command_t.class))
            return 0L;
 
        classes.add(kinect.lcmtypes.robot_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        outs.writeByte( this.updateDest ? 1 : 0); 
 
        for (int a = 0; a < 6; a++) {
            outs.writeDouble(this.dest[a]); 
        }
 
        __strbuf = new char[this.action.length()]; this.action.getChars(0, this.action.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public robot_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public robot_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static kinect.lcmtypes.robot_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        kinect.lcmtypes.robot_command_t o = new kinect.lcmtypes.robot_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.updateDest = ins.readByte()!=0;
 
        this.dest = new double[(int) 6];
        for (int a = 0; a < 6; a++) {
            this.dest[a] = ins.readDouble();
        }
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.action = new String(__strbuf);
 
    }
 
    public kinect.lcmtypes.robot_command_t copy()
    {
        kinect.lcmtypes.robot_command_t outobj = new kinect.lcmtypes.robot_command_t();
        outobj.utime = this.utime;
 
        outobj.updateDest = this.updateDest;
 
        outobj.dest = new double[(int) 6];
        System.arraycopy(this.dest, 0, outobj.dest, 0, 6); 
        outobj.action = this.action;
 
        return outobj;
    }
 
}

